Distribute points on array

In [10]:
import numpy as np
x = 10    # size of diagramm
y = 20
d = 4     # number of points in x direction

a = np.linspace(0, x, num=d, dtype=np.uint16)
a

array([ 0,  3,  6, 10], dtype=uint16)

In [2]:
b = np.linspace(0, y, num=int(d*y / x), dtype=np.uint16)
b

array([ 0,  2,  5,  8, 11, 14, 17, 20], dtype=uint16)

In [11]:
np.full((8,4), a).T.flatten()

array([ 0,  0,  0,  0,  0,  0,  0,  0,  3,  3,  3,  3,  3,  3,  3,  3,  6,
        6,  6,  6,  6,  6,  6,  6, 10, 10, 10, 10, 10, 10, 10, 10],
      dtype=uint16)

In [4]:
np.full((4,8), b).flatten()

array([ 0,  2,  5,  8, 11, 14, 17, 20,  0,  2,  5,  8, 11, 14, 17, 20,  0,
        2,  5,  8, 11, 14, 17, 20,  0,  2,  5,  8, 11, 14, 17, 20],
      dtype=uint16)

In [16]:
l = np.column_stack((np.full((8,4), a).T.flatten(), np.full((4,8), b).flatten()))
for i in l: print(i)

[0 0]
[0 2]
[0 5]
[0 8]
[ 0 11]
[ 0 14]
[ 0 17]
[ 0 20]
[3 0]
[3 2]
[3 5]
[3 8]
[ 3 11]
[ 3 14]
[ 3 17]
[ 3 20]
[6 0]
[6 2]
[6 5]
[6 8]
[ 6 11]
[ 6 14]
[ 6 17]
[ 6 20]
[10  0]
[10  2]
[10  5]
[10  8]
[10 11]
[10 14]
[10 17]
[10 20]


In [6]:
a = np.array([1,2,3])
aa = np.array([1,1,1,2,2,2,3,3,3])
bb = np.array([1,2,3,1,2,3,1,2,3])


In [19]:
a = np.zeros((3,3), dtype=np.uint16)
a
a[1]=[3,4,5]
a

array([[0, 0, 0],
       [3, 4, 5],
       [0, 0, 0]], dtype=uint16)