# Mein Beispiel
soll dem Florin und mir zeigen, wie man den average aus einem einfachen dreieck (mit Mask) holt
## Bild herstellen

In [1]:
import numpy as np
import cv2 as cv

img = np.zeros((1,9,3), dtype = np.uint8)
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

jetzt immer auf den 3 Kanälen den 0.ten (Blau) auf 1 setzen

In [2]:
img[:,:,[0]] = 1
img

array([[[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]]], dtype=uint8)

Achtung, der Slice hat die Shape des arrays

In [3]:
img[:,:,[0]]

array([[[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]]], dtype=uint8)

Entsprechend muss die Arrayzuordnung im selben shape sein

In [4]:
img[:,:,[0]] = np.arange(0,90,10).reshape(1,9,1)
img

array([[[ 0,  0,  0],
        [10,  0,  0],
        [20,  0,  0],
        [30,  0,  0],
        [40,  0,  0],
        [50,  0,  0],
        [60,  0,  0],
        [70,  0,  0],
        [80,  0,  0]]], dtype=uint8)

## contour rausholen (mit mask) 

In [5]:
mask = np.zeros(img.shape[:2], dtype="uint8")
cv.circle(mask, (3, 0),1,255,-1)
mask        

array([[  0,   0, 255, 255, 255,   0,   0,   0,   0]], dtype=uint8)

In [6]:
masked = cv.bitwise_and(img, img, mask=mask)
masked

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [20,  0,  0],
        [30,  0,  0],
        [40,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

In [7]:
np.average(masked[:,:,0])

10.0

die (gemaskten) nullen stören den Schnitt

## mit numpy maskieren

In [8]:
nm = np.ma.masked_where(mask == 0, img[:,:,0])
nm

masked_array(data=[[--, --, 20, 30, 40, --, --, --, --]],
             mask=[[ True,  True, False, False, False,  True,  True,
                     True,  True]],
       fill_value=999999,
            dtype=uint8)

In [9]:
np.average(nm)

30.0

In [10]:
np.mean(nm)

30.0

In [14]:
np.sqrt(np.var(nm))

8.16496580927726